default_voice_settings = {
 'af-ZA': {'languageCode': 'af-ZA',
  'name': 'af-ZA-Standard-A',
  'ssmlGender': 'FEMALE'},
 'ar-XA': {'languageCode': 'ar-XA',
  'name': 'ar-XA-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'eu-ES': {'languageCode': 'eu-ES',
  'name': 'eu-ES-Standard-A',
  'ssmlGender': 'FEMALE'},
 'bn-IN': {'languageCode': 'bn-IN',
  'name': 'bn-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'bg-BG': {'languageCode': 'bg-BG',
  'name': 'bg-BG-Standard-A',
  'ssmlGender': 'FEMALE'},
 'ca-ES': {'languageCode': 'ca-ES',
  'name': 'ca-ES-Standard-A',
  'ssmlGender': 'FEMALE'},
 'yue-HK': {'languageCode': 'yue-HK',
  'name': 'yue-HK-Standard-A',
  'ssmlGender': 'MALE'},
 'cs-CZ': {'languageCode': 'cs-CZ',
  'name': 'cs-CZ-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'da-DK': {'languageCode': 'da-DK',
  'name': 'da-DK-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'nl-BE': {'languageCode': 'nl-BE',
  'name': 'nl-BE-Wavenet-A',
  'ssmlGender': 'MALE'},
 'nl-NL': {'languageCode': 'nl-NL',
  'name': 'nl-NL-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'en-AU': {'languageCode': 'en-AU',
  'name': 'en-AU-Wavenet-A',
  'ssmlGender': 'MALE'},
 'en-IN': {'languageCode': 'en-IN',
  'name': 'en-IN-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'en-GB': {'languageCode': 'en-GB',
  'name': 'en-GB-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'en-US': {'languageCode': 'en-US',
  'name': 'en-US-Wavenet-A',
  'ssmlGender': 'MALE'},
 'fil-PH': {'languageCode': 'fil-PH',
  'name': 'fil-ph-Neural2-A',
  'ssmlGender': 'MALE'},
 'fi-FI': {'languageCode': 'fi-FI',
  'name': 'fi-FI-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'fr-CA': {'languageCode': 'fr-CA',
  'name': 'fr-CA-Wavenet-A',
  'ssmlGender': 'MALE'},
 'fr-FR': {'languageCode': 'fr-FR',
  'name': 'fr-FR-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'gl-ES': {'languageCode': 'gl-ES',
  'name': 'gl-ES-Standard-A',
  'ssmlGender': 'FEMALE'},
 'de-DE': {'languageCode': 'de-DE',
  'name': 'de-DE-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'el-GR': {'languageCode': 'el-GR',
  'name': 'el-GR-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'gu-IN': {'languageCode': 'gu-IN',
  'name': 'gu-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'he-IL': {'languageCode': 'he-IL',
  'name': 'he-IL-Wavenet-A',
  'ssmlGender': 'MALE'},
 'hi-IN': {'languageCode': 'hi-IN',
  'name': 'hi-IN-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'hu-HU': {'languageCode': 'hu-HU',
  'name': 'hu-HU-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'is-IS': {'languageCode': 'is-IS',
  'name': 'is-IS-Standard-A',
  'ssmlGender': 'FEMALE'},
 'id-ID': {'languageCode': 'id-ID',
  'name': 'id-ID-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'it-IT': {'languageCode': 'it-IT',
  'name': 'it-IT-Wavenet-A',
  'ssmlGender': 'MALE'},
 'ja-JP': {'languageCode': 'ja-JP',
  'name': 'ja-JP-Wavenet-A',
  'ssmlGender': 'MALE'},
 'kn-IN': {'languageCode': 'kn-IN',
  'name': 'kn-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'ko-KR': {'languageCode': 'ko-KR',
  'name': 'ko-KR-Wavenet-A',
  'ssmlGender': 'MALE'},
 'lv-LV': {'languageCode': 'lv-LV',
  'name': 'lv-LV-Standard-A',
  'ssmlGender': 'MALE'},
 'lt-LT': {'languageCode': 'lt-LT',
  'name': 'lt-LT-Standard-A',
  'ssmlGender': 'MALE'},
 'ms-MY': {'languageCode': 'ms-MY',
  'name': 'ms-MY-Wavenet-A',
  'ssmlGender': 'MALE'},
 'ml-IN': {'languageCode': 'ml-IN',
  'name': 'ml-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'cmn-CN': {'languageCode': 'cmn-CN',
  'name': 'cmn-CN-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'cmn-TW': {'languageCode': 'cmn-TW',
  'name': 'cmn-TW-Wavenet-A',
  'ssmlGender': 'MALE'},
 'mr-IN': {'languageCode': 'mr-IN',
  'name': 'mr-IN-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'nb-NO': {'languageCode': 'nb-NO',
  'name': 'nb-NO-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'pl-PL': {'languageCode': 'pl-PL',
  'name': 'pl-PL-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'pt-BR': {'languageCode': 'pt-BR',
  'name': 'pt-BR-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'pt-PT': {'languageCode': 'pt-PT',
  'name': 'pt-PT-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'pa-IN': {'languageCode': 'pa-IN',
  'name': 'pa-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'ro-RO': {'languageCode': 'ro-RO',
  'name': 'ro-RO-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'ru-RU': {'languageCode': 'ru-RU',
  'name': 'ru-RU-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'sr-RS': {'languageCode': 'sr-RS',
  'name': 'sr-RS-Standard-A',
  'ssmlGender': 'FEMALE'},
 'sk-SK': {'languageCode': 'sk-SK',
  'name': 'sk-SK-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'es-ES': {'languageCode': 'es-ES',
  'name': 'es-ES-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'es-US': {'languageCode': 'es-US',
  'name': 'es-US-Wavenet-A',
  'ssmlGender': 'MALE'},
 'sv-SE': {'languageCode': 'sv-SE',
  'name': 'sv-SE-Wavenet-A',
  'ssmlGender': 'MALE'},
 'ta-IN': {'languageCode': 'ta-IN',
  'name': 'ta-IN-Wavenet-A',
  'ssmlGender': 'MALE'},
 'te-IN': {'languageCode': 'te-IN',
  'name': 'te-IN-Standard-A',
  'ssmlGender': 'MALE'},
 'th-TH': {'languageCode': 'th-TH',
  'name': 'th-TH-Standard-A',
  'ssmlGender': 'FEMALE'},
 'tr-TR': {'languageCode': 'tr-TR',
  'name': 'tr-TR-Wavenet-A',
  'ssmlGender': 'MALE'},
 'uk-UA': {'languageCode': 'uk-UA',
  'name': 'uk-UA-Wavenet-A',
  'ssmlGender': 'FEMALE'},
 'vi-VN': {'languageCode': 'vi-VN',
  'name': 'vi-VN-Wavenet-A',
  'ssmlGender': 'MALE'}
} # end default_voice_settings
